apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: niro-map-postgres
  namespace: personal
spec:
  serviceName: 'niro-map-postgres-service'
  replicas: 1
  selector:
    matchLabels:
      app: niro-map-postgres
  template:
    metadata:
      labels:
        app: niro-map-postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: niro-map-postgres-secret
          env:
            - name: POSTGRES_DB
              value: 'niromap_db'
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: '250m' # Request 0.25 CPU cores
              memory: '512Mi' # Request 0.5 GiB of RAM
            limits:
              cpu: '1'
              memory: '1536Mi'
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ['pg_isready', '-U', 'niro58', '-d', 'niromap_db'] # <-- CHANGE USERNAME
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ['pg_isready', '-U', 'niro58', '-d', 'niromap_db'] # <-- CHANGE USERNAME
            initialDelaySeconds: 45
            periodSeconds: 20

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 15Gi
